name: 🐛 Reportar Bug
description: Crie um relatório para nos ajudar a corrigir problemas
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar! Preencha os detalhes abaixo para nos ajudar a reproduzir o erro.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: O que aconteceu de errado?
      placeholder: "Ex: Ao clicar no botão salvar, a tela ficou branca..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Liste os passos exatos para o erro acontecer.
      placeholder: |
        1. Acesse a página X
        2. Clique no botão Y
        3. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria ter acontecido?
      placeholder: "Ex: O formulário deveria ter sido salvo e mostrado uma mensagem de sucesso."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Ambiente (Navegador/Sistema)
      description: Qual navegador, versão ou sistema operacional você está usando?
      placeholder: "Ex: Chrome 98, Windows 10"
    validations:
      required: false

  - type: checkboxes
    id: screenshots
    attributes:
      label: Evidências
      options:
        - label: Anexei prints ou vídeos do erro (se aplicável)
