name: ✨Solicitação de Funcionalidade
description: Solicite uma nova funcionalidade ou melhoria
labels: ["enhancement"]
title: "[FEAT]: "
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher esta solicitação de funcionalidade 🤗  
        Certifique-se de que não há nenhuma issue aberta/fechada relacionada a este problema 😃

  - type: textarea
    id: goal
    attributes:
      label: Objetivo
      description: Descreva o objetivo principal dessa funcionalidade ou melhoria
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Contexto
      description: Forneça o contexto ou o problema que motiva a solicitação dessa funcionalidade
    validations:
      required: false

  - type: textarea
    id: requirements
    attributes:
      label: Requisitos
      description: Liste os requisitos técnicos ou funcionais necessários para implementar esta funcionalidade
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Critérios de Aceite
      description: Descreva os critérios que devem ser atendidos para considerar a funcionalidade como concluída
    validations:
      required: false

 - type: checkboxes
    id: checklist-dod
    attributes:
      label: Checklist de DoD (Definition of Done)
      description: Marque os itens que foram concluídos para esta tarefa.
      options:
        - label: A funcionalidade foi feita
        - label: O código foi revisado
        - label: Todos os testes necessários foram realizados
        - label: O MR foi aprovado
    validations:
      required: true
