name: 🚀 Nova Funcionalidade (Feature)
description: Sugira uma ideia para este projeto
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma ideia! Por favor, preencha os campos abaixo.

  - type: textarea
    id: problem
    attributes:
      label: Qual é a dor ou problema relacionado?
      description: Uma descrição clara e concisa de qual é o problema.
      placeholder: "Ex: Eu fico frustrado quando tento clicar no botão e..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Descreva a solução que você gostaria
      description: O que você quer que aconteça?
      placeholder: "Ex: Gostaria que o botão ficasse azul..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Critérios de Aceite
      options:
        - label: O código compila sem erros
        - label: Testes foram adicionados
